version: '3.9'

services:
  db:
    image: postgres:13-alpine
    container_name: postgres_go_admin_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
